name: Lesson 5 SAST

on:
  push:
    branches:
      - lesson-5

jobs:
  security_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    name: Run pycharm security test
    steps:
      - uses: actions/checkout@v4
      - name: Run pycharm security test
        uses: tonybaloney/pycharm-security@1.25.1

  deploy:
    needs: security_test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Disable Debug
        run: |
          sed -i 's/DEBUG = True/DEBUG = False/g' hangry_api/hangry_api/settings.py
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: '**PLACEHOLDER** Deploy to Elastic Beanstalk'
        run: echo Placeholder for Deployment